import { theme as antdTheme, type ThemeConfig } from 'antd';
import type { ThemePalette } from '@renderer/theme/app-theme.types';
import type { AppThemeMode } from '@renderer/store/ui-store.types';

const FONT_FAMILY = "Inter, 'Segoe UI', Arial, sans-serif";
const BORDER_RADIUS = 18;
const BORDER_RADIUS_SMALL = 12;
const BORDER_RADIUS_XS = 8;

const THEME_PALETTES: Record<AppThemeMode, ThemePalette> = {
  dark: {
    colorScheme: 'dark',
    appBg: '#0b1220',
    layoutBg: '#0b1220',
    surface: '#111a2b',
    surfaceAlt: '#162133',
    surfaceMuted: '#0f1724',
    elevated: '#162133',
    border: '#23324a',
    borderStrong: '#314562',
    text: '#e6edf7',
    textSecondary: '#9babbe',
    textMuted: '#7f8ea2',
    heading: '#f3f7fd',
    primary: '#4f8cff',
    primaryHover: '#6b9cff',
    primaryActive: '#3d74db',
    primarySoft: '#162744',
    primarySoftHover: '#1b3152',
    success: '#2f9e71',
    warning: '#d79a2b',
    error: '#d96570',
    info: '#4f8cff',
    icon: '#8ea0b7',
    iconHover: '#d7e1ee',
    spotlight: '#162133',
    scrollbarTrack: '#101826',
    scrollbarThumb: '#314562',
    scrollbarThumbHover: '#425b7f',
  },
  light: {
    colorScheme: 'light',
    appBg: '#eef3fa',
    layoutBg: '#eef3fa',
    surface: '#ffffff',
    surfaceAlt: '#f5f8fc',
    surfaceMuted: '#edf2f8',
    elevated: '#ffffff',
    border: '#d5deeb',
    borderStrong: '#b7c5d8',
    text: '#122033',
    textSecondary: '#5d6d82',
    textMuted: '#74849a',
    heading: '#091423',
    primary: '#2f6fe4',
    primaryHover: '#4d87ee',
    primaryActive: '#255ec4',
    primarySoft: '#e8f0ff',
    primarySoftHover: '#dae7ff',
    success: '#27855f',
    warning: '#b47a16',
    error: '#c94a59',
    info: '#2f6fe4',
    icon: '#5d6d82',
    iconHover: '#122033',
    spotlight: '#162133',
    scrollbarTrack: '#dde6f1',
    scrollbarThumb: '#b7c5d8',
    scrollbarThumbHover: '#94a8c3',
  },
};

const createThemeConfig = (palette: ThemePalette, mode: AppThemeMode): ThemeConfig => ({
  algorithm: mode === 'dark' ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
  hashed: false,
  cssVar: {
    prefix: 'dsk-video-merger',
    key: mode,
  },
  token: {
    wireframe: false,
    fontFamily: FONT_FAMILY,
    colorPrimary: palette.primary,
    colorInfo: palette.info,
    colorSuccess: palette.success,
    colorWarning: palette.warning,
    colorError: palette.error,
    colorLink: palette.primary,
    colorLinkHover: palette.primaryHover,
    colorLinkActive: palette.primaryActive,
    colorBgBase: palette.layoutBg,
    colorBgLayout: palette.layoutBg,
    colorBgContainer: palette.surface,
    colorBgElevated: palette.elevated,
    colorBgSpotlight: palette.spotlight,
    colorBgContainerDisabled: palette.surfaceMuted,
    colorFill: palette.surfaceAlt,
    colorFillSecondary: palette.surfaceAlt,
    colorFillTertiary: palette.surfaceMuted,
    colorFillQuaternary: palette.surfaceMuted,
    colorFillAlter: palette.surfaceAlt,
    colorFillContent: palette.surfaceMuted,
    colorFillContentHover: palette.surfaceAlt,
    colorText: palette.text,
    colorTextSecondary: palette.textSecondary,
    colorTextTertiary: palette.textMuted,
    colorTextQuaternary: palette.textMuted,
    colorTextLabel: palette.textSecondary,
    colorTextDescription: palette.textSecondary,
    colorTextHeading: palette.heading,
    colorTextPlaceholder: palette.textMuted,
    colorTextDisabled: palette.textMuted,
    colorTextLightSolid: '#f8fbff',
    colorBorder: palette.border,
    colorBorderSecondary: palette.border,
    colorSplit: palette.border,
    colorBorderBg: palette.border,
    colorPrimaryBg: palette.primarySoft,
    colorPrimaryBgHover: palette.primarySoftHover,
    colorPrimaryBorder: palette.primary,
    colorPrimaryBorderHover: palette.primaryHover,
    colorIcon: palette.icon,
    colorIconHover: palette.iconHover,
    controlItemBgHover: palette.surfaceAlt,
    controlItemBgActive: palette.primarySoft,
    controlItemBgActiveHover: palette.primarySoftHover,
    controlItemBgActiveDisabled: palette.surfaceMuted,
    controlOutline: 'transparent',
    controlOutlineWidth: 0,
    lineWidth: 1,
    lineWidthFocus: 1,
    borderRadius: BORDER_RADIUS_SMALL,
    borderRadiusSM: BORDER_RADIUS_XS,
    borderRadiusLG: BORDER_RADIUS,
    borderRadiusXS: 6,
    boxShadow: 'none',
    boxShadowSecondary: 'none',
    boxShadowTertiary: 'none',
  },
  components: {
    Layout: {
      bodyBg: 'transparent',
      headerBg: 'transparent',
      footerBg: 'transparent',
      siderBg: palette.surface,
      triggerBg: palette.surfaceAlt,
      triggerColor: palette.text,
      headerColor: palette.text,
      headerHeight: 72,
    },
    Card: {
      headerBg: 'transparent',
      actionsBg: palette.surfaceAlt,
      extraColor: palette.textSecondary,
      bodyPadding: 24,
      headerPadding: 24,
      headerHeight: 60,
    },
    Button: {
      fontWeight: 500,
      iconGap: 8,
      defaultShadow: 'none',
      primaryShadow: 'none',
      dangerShadow: 'none',
      defaultBg: palette.surfaceAlt,
      defaultColor: palette.text,
      defaultBorderColor: palette.border,
      defaultHoverBg: palette.surfaceMuted,
      defaultHoverColor: palette.heading,
      defaultHoverBorderColor: palette.borderStrong,
      defaultActiveBg: palette.surfaceMuted,
      defaultActiveColor: palette.heading,
      defaultActiveBorderColor: palette.borderStrong,
      primaryColor: '#f8fbff',
      solidTextColor: '#f8fbff',
      defaultGhostColor: palette.text,
      defaultGhostBorderColor: palette.border,
      ghostBg: 'transparent',
      textTextColor: palette.textSecondary,
      textTextHoverColor: palette.heading,
      textTextActiveColor: palette.heading,
      textHoverBg: palette.surfaceAlt,
      linkHoverBg: 'transparent',
      borderColorDisabled: palette.border,
      paddingInline: 16,
      paddingInlineSM: 12,
      paddingInlineLG: 20,
      paddingBlock: 6,
      paddingBlockSM: 4,
      paddingBlockLG: 9,
      contentFontSize: 14,
      contentFontSizeSM: 13,
      contentFontSizeLG: 15,
    },
    Input: {
      addonBg: palette.surfaceAlt,
      hoverBorderColor: palette.borderStrong,
      activeBorderColor: palette.primary,
      activeShadow: 'none',
      errorActiveShadow: 'none',
      warningActiveShadow: 'none',
      hoverBg: palette.surfaceAlt,
      activeBg: palette.surface,
      paddingBlock: 7,
      paddingBlockLG: 10,
      paddingBlockSM: 4,
      paddingInline: 12,
      paddingInlineLG: 14,
      paddingInlineSM: 10,
    },
    Select: {
      selectorBg: palette.surfaceAlt,
      clearBg: palette.surfaceAlt,
      hoverBorderColor: palette.borderStrong,
      activeBorderColor: palette.primary,
      activeOutlineColor: 'transparent',
      optionActiveBg: palette.surfaceMuted,
      optionSelectedBg: palette.primarySoft,
      optionSelectedColor: palette.heading,
      optionSelectedFontWeight: 500,
      multipleItemBg: palette.surfaceMuted,
      multipleItemBorderColor: palette.border,
      multipleSelectorBgDisabled: palette.surfaceMuted,
      multipleItemColorDisabled: palette.textMuted,
      multipleItemBorderColorDisabled: palette.border,
    },
    Segmented: {
      trackBg: palette.surfaceAlt,
      trackPadding: 4,
      itemColor: palette.textSecondary,
      itemHoverColor: palette.heading,
      itemHoverBg: palette.surfaceMuted,
      itemActiveBg: palette.surfaceMuted,
      itemSelectedBg: palette.primarySoft,
      itemSelectedColor: palette.heading,
    },
    Tag: {
      defaultBg: palette.surfaceAlt,
      defaultColor: palette.textSecondary,
    },
    Table: {
      headerBg: palette.surfaceAlt,
      headerColor: palette.textSecondary,
      headerSortActiveBg: palette.surfaceMuted,
      headerSortHoverBg: palette.surfaceMuted,
      bodySortBg: palette.surfaceAlt,
      rowHoverBg: palette.surfaceAlt,
      rowSelectedBg: palette.primarySoft,
      rowSelectedHoverBg: palette.primarySoftHover,
      rowExpandedBg: palette.surfaceAlt,
      borderColor: palette.border,
      headerSplitColor: palette.border,
      headerBorderRadius: BORDER_RADIUS_SMALL,
      footerBg: palette.surfaceAlt,
      footerColor: palette.textSecondary,
      fixedHeaderSortActiveBg: palette.surfaceMuted,
      headerFilterHoverBg: palette.surfaceMuted,
      filterDropdownMenuBg: palette.surface,
      filterDropdownBg: palette.surface,
      expandIconBg: palette.surfaceAlt,
      stickyScrollBarBg: palette.scrollbarThumb,
      stickyScrollBarBorderRadius: 999,
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
      cellPaddingBlockMD: 12,
      cellPaddingInlineMD: 14,
      cellPaddingBlockSM: 10,
      cellPaddingInlineSM: 12,
    },
    Modal: {
      headerBg: palette.surface,
      contentBg: palette.surface,
      footerBg: palette.surface,
      titleColor: palette.heading,
      titleFontSize: 18,
    },
    Drawer: {
      footerPaddingBlock: 18,
      footerPaddingInline: 24,
    },
    Progress: {
      defaultColor: palette.primary,
      remainingColor: palette.surfaceMuted,
      lineBorderRadius: 999,
    },
    Alert: {
      defaultPadding: '12px 14px',
      withDescriptionPadding: '14px 16px',
      withDescriptionIconSize: 18,
    },
    Descriptions: {
      labelBg: palette.surfaceAlt,
      labelColor: palette.textSecondary,
      titleColor: palette.heading,
      contentColor: palette.text,
      extraColor: palette.textSecondary,
      itemPaddingBottom: 14,
    },
    Steps: {
      navArrowColor: palette.borderStrong,
      titleLineHeight: 1.3,
      iconSize: 30,
      iconFontSize: 15,
      dotSize: 8,
      dotCurrentSize: 10,
      customIconSize: 30,
      customIconFontSize: 16,
    },
    Tooltip: {
      zIndexPopup: 1200,
    },
    List: {
      headerBg: 'transparent',
      footerBg: 'transparent',
      itemPadding: '14px 0',
      itemPaddingLG: '18px 0',
      itemPaddingSM: '10px 0',
      descriptionFontSize: 13,
    },
    Statistic: {
      titleFontSize: 13,
      contentFontSize: 30,
    },
    Avatar: {
      groupBorderColor: palette.surface,
    },
    Divider: {
      colorSplit: palette.border,
    },
  },
});

export const getThemePalette = (mode: AppThemeMode): ThemePalette => THEME_PALETTES[mode];

export const getAntdThemeConfig = (mode: AppThemeMode): ThemeConfig =>
  createThemeConfig(getThemePalette(mode), mode);

export const applyThemeCssVariables = (mode: AppThemeMode): void => {
  if (typeof document === 'undefined') {
    return;
  }

  const palette = getThemePalette(mode);
  const root = document.documentElement;

  root.style.setProperty('--app-bg', palette.appBg);
  root.style.setProperty('--app-layout-bg', palette.layoutBg);
  root.style.setProperty('--app-surface', palette.surface);
  root.style.setProperty('--app-surface-alt', palette.surfaceAlt);
  root.style.setProperty('--app-surface-muted', palette.surfaceMuted);
  root.style.setProperty('--app-border', palette.border);
  root.style.setProperty('--app-border-strong', palette.borderStrong);
  root.style.setProperty('--app-text', palette.text);
  root.style.setProperty('--app-text-secondary', palette.textSecondary);
  root.style.setProperty('--app-accent', palette.primary);
  root.style.setProperty('--app-accent-soft', palette.primarySoft);
  root.style.setProperty('--app-status-bg', palette.surfaceAlt);
  root.style.setProperty('--app-status-border', palette.borderStrong);
  root.style.setProperty('--app-avatar-bg', palette.primarySoft);
  root.style.setProperty('--app-scrollbar-track', palette.scrollbarTrack);
  root.style.setProperty('--app-scrollbar-thumb', palette.scrollbarThumb);
  root.style.setProperty('--app-scrollbar-thumb-hover', palette.scrollbarThumbHover);
  root.style.setProperty('color-scheme', palette.colorScheme);
};
