import { theme, type ThemeConfig } from 'antd';

export const siteTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  hashed: false,
  token: {
    fontFamily: "Inter, 'Segoe UI', sans-serif",
    colorPrimary: '#5ce1e6',
    colorInfo: '#5ce1e6',
    colorSuccess: '#56d18d',
    colorWarning: '#f5b942',
    colorError: '#ff6f7d',
    colorBgBase: '#05070b',
    colorBgLayout: '#05070b',
    colorBgContainer: '#0b1020',
    colorBgElevated: '#0e1326',
    colorText: '#f4f7fb',
    colorTextSecondary: '#9fb0c7',
    colorTextHeading: '#ffffff',
    colorBorder: '#202c42',
    colorBorderSecondary: '#202c42',
    colorSplit: '#202c42',
    borderRadius: 20,
    borderRadiusLG: 24,
    borderRadiusSM: 14,
    boxShadow: 'none',
    boxShadowSecondary: 'none',
  },
  components: {
    Layout: {
      bodyBg: 'transparent',
      headerBg: 'transparent',
      footerBg: 'transparent',
    },
    Card: {
      bodyPadding: 24,
      headerPadding: 24,
      headerHeight: 60,
      colorBorderSecondary: '#25324b',
    },
    Button: {
      borderRadius: 999,
      controlHeight: 44,
      controlHeightLG: 52,
      defaultBg: '#0e1526',
      defaultBorderColor: '#24324a',
      defaultColor: '#f4f7fb',
      defaultHoverBg: '#131c31',
      defaultHoverColor: '#ffffff',
      defaultHoverBorderColor: '#334664',
      defaultActiveBg: '#131c31',
      defaultActiveBorderColor: '#334664',
      primaryColor: '#031318',
      solidTextColor: '#031318',
      defaultShadow: 'none',
      primaryShadow: 'none',
    },
    Tag: {
      defaultBg: '#0e1526',
      defaultColor: '#c7d3e3',
    },
    Statistic: {
      titleFontSize: 13,
      contentFontSize: 28,
    },
    Segmented: {
      trackBg: '#09111f',
      itemColor: '#9fb0c7',
      itemHoverColor: '#ffffff',
      itemHoverBg: '#111a2c',
      itemSelectedBg: '#5ce1e6',
      itemSelectedColor: '#031318',
    },
  },
};
