import { theme, type ThemeConfig } from 'antd';

export const siteTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  hashed: false,
  token: {
    fontFamily: "Inter, 'Segoe UI', sans-serif",
    colorPrimary: '#7fa8ff',
    colorInfo: '#7fa8ff',
    colorSuccess: '#56c78d',
    colorWarning: '#e5ac48',
    colorError: '#ff7384',
    colorBgBase: '#04070d',
    colorBgLayout: '#04070d',
    colorBgContainer: '#0b1220',
    colorBgElevated: '#0d1526',
    colorText: '#f5f7fb',
    colorTextSecondary: '#97a6bb',
    colorTextHeading: '#ffffff',
    colorBorder: '#1e2b42',
    colorBorderSecondary: '#1e2b42',
    colorSplit: '#1e2b42',
    borderRadius: 24,
    borderRadiusLG: 28,
    borderRadiusSM: 16,
    boxShadow: 'none',
    boxShadowSecondary: 'none',
  },
  components: {
    Layout: {
      bodyBg: 'transparent',
      headerBg: 'transparent',
      footerBg: 'transparent',
    },
    Button: {
      borderRadius: 999,
      controlHeight: 44,
      controlHeightLG: 50,
      defaultBg: '#0d1526',
      defaultBorderColor: '#25344d',
      defaultColor: '#f5f7fb',
      defaultHoverBg: '#121d33',
      defaultHoverColor: '#ffffff',
      defaultHoverBorderColor: '#314560',
      defaultActiveBg: '#121d33',
      defaultActiveBorderColor: '#314560',
      primaryColor: '#0a1020',
      solidTextColor: '#0a1020',
      defaultShadow: 'none',
      primaryShadow: 'none',
    },
    Tag: {
      defaultBg: '#0d1526',
      defaultColor: '#d5ddea',
    },
  },
};
